name: data
on: [push]
jobs:
  create-patches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download-images
        run: |
          chmod +x scripts/install_data.sh
          scripts/install_data.sh

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: slice-image
        run: |
          cd src
          pip install poetry
          poetry install --only patch --no-root
          poetry run python patch.py

      - name: save-train
        uses: actions/upload-artifact@v4
        with:
          name: train
          path: data/train

      - name: save-val
        uses: actions/upload-artifact@v4
        with:
          name: val
          path: data/val

      - name: save-test
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: data/test

  train:
    needs: [create-patches]
    runs-on: ubuntu-latest
    steps:
        - run: mkdir data && cd data
        - uses: actions/download-artifact@v4
          with:
            name: train
        - run: ls -l .

            
