name: data
on: [push]
jobs:
  create-patches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download-images
        run: |
          chmod +x scripts/install_data.sh
          scripts/install_data.sh

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: slice-image
        run: |
          cd src
          pip install poetry
          poetry install --only patch --no-root
          poetry run python src/patch.py

      - name: archive-patches
        run: |
          zip -r train.zip data/train/
          zip -r val.zip data/vat/
          zip -r test.zip data/test/

      - name: save-train
        uses: actions/upload-artifact@v4
        with:
          name: train
          path: |
            train.zip

      - name: save-val
        uses: actions/upload-artifact@v4
        with:
          name: val
          path: |
            val.zip

      - name: save-test
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            test.zip
            
